### ISSUE TITLE
ping_pong app not so right on my board

### ISSUE THREAD

**Issue by Needrom** [micro-ROS/micro_ros_setup#287]
## Issue template

- Hardware description: https://github.com/Needrom/Microros-on-DIscovery-board
- RTOS: freertos
- Installation type: micro_ros_setup
- Version or commit hash: foxy

#### Steps to reproduce the issue
run ``` ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 ```
and echo the topic ```/microROS/ping```

#### Expected behavior
it should any way print the message until I kill the process or trun off my board.

#### Actual behavior
the topic just print a little.The message down below is all it printf.
```
stamp:
  sec: 4
  nanosec: 640000000
frame_id: '467594128_37129206'
---
stamp:
  sec: 6
  nanosec: 633000000
frame_id: '1691377550_37129206'
---
stamp:
  sec: 8
  nanosec: 636000000
frame_id: '1471595416_37129206'
---
stamp:
  sec: 10
  nanosec: 632000000
frame_id: '262628173_37129206'
---
stamp:
  sec: 12
  nanosec: 635000000
frame_id: '1198695175_37129206'
---
stamp:
  sec: 14
  nanosec: 632000000
frame_id: '636211359_37129206'
---
stamp:
  sec: 16
  nanosec: 634000000
frame_id: '1129188923_37129206'
---
stamp:
  sec: 18
  nanosec: 632000000
frame_id: '60369457_37129206'
---



```
